name: PHP Composer

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.0, 8.1]
        os: [ubuntu-latest, macos-latest, windows-latest]
        composer: [v1, v2]
    name: PHP ${{ matrix.php }} - OS ${{ matrix.os }} - Composer ${{ matrix.composer }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
            path: |
              ~/.composer/cache/files
              ~/.composer/cache/repo
            key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: curl, zip
            coverage: pcov
            tools: composer:${{ matrix.composer }}
      - name: Validate composer.json
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --diff --dry-run
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v
        if: ${{ github.event_name == 'push' && matrix.php == '8.1' }}
